---
- hosts: all
  sudo: yes
  remote_user: ubuntu


  vars:
    production: false
    full_server_url: http://localhost:9000
    jaci_http_hostname: jaci.io
    jaci_http_port: 5000
    jaci_web_processes: 2
    jaci_github_client_id: 1c061315e9b34dc153aa
    jaci_github_client_secret: 5c9909556b60f3e6c618f278230620415cc15da8
    docker_version: 1.6.1
    docker_admin_users: []
    docker_opts:
      - "--iptables=false"

  tasks:
    - include_vars: ansible/vars-prod.yml
      when: production

    - include_vars: ansible/vars-vault.yml
      when: production

    - name: ensure apt is ok
      shell: dpkg --configure -a
      ignore_errors: yes

    - name: install docker dependencies
      apt: pkg={{ item }} state=present
      with_items:
        - linux-image-extra-virtual

    - name: add git core ppa
      apt_repository: repo='ppa:git-core'

    - name: install jaci dependencies
      apt:
        pkg: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - bash-completion
        - python-dev
        - libffi-dev
        - libssl-dev
        - libgnutls-dev
        - libsqlite3-dev
        - python-pip
        - python-virtualenv
        - git-core
        - nginx


    - name: add docker repository key
      apt_key: url=https://get.docker.io/gpg state=present

    - name: add docker repository
      apt_repository: >-
        repo="deb http://get.docker.io/ubuntu docker main" state=present

    - name: install docker
      apt: >-
        pkg=lxc-docker-{{ docker_version }}
        state=latest update_cache=yes cache_valid_time=3600

    - name: ensuring that the jaci-workers builds dir is present
      file: path=/srv/jaci/builds state=directory

    - name: ensuring that the jaci-workers ssh-keys dir is present
      file: path=/srv/jaci/ssh-keys state=directory

    - name: ensuring that the cassandra data dir is present
      file: path=/srv/jaci/data state=directory

    - name: ensuring that the assets dir exists
      file: path=/srv/jaci/assets state=directory

    - name: ensuring that the log dirs exist
      file: path={{ item }} state=directory
      with_items:
        - /var/log/jaci-web
        - /var/log/jaci-workers

    - name: update docker defaults file
      template: src=ansible/docker.default.j2 dest=/etc/default/docker

    - name: add admin users to docker group
      user: name={{ item }} groups=docker append=yes
      with_items: docker_admin_users

    - name: start docker
      service: name=docker state=restarted
      ignore_errors: yes

    - name: stop jaci-web
      service: name=jaci-web state=stopped
      ignore_errors: yes

    - name: stop jaci-workers
      service: name=jaci-workers state=stopped

    - name: ensure docker is clean
      shell: docker kill -s 9 $(docker ps -qa)
      ignore_errors: yes

    - name: install the cassandra upstart
      template: src=ansible/cassandra.upstart.j2
        dest=/etc/init/cassandra.conf
        owner=root group=root mode=644
      tags:
        - upstart

    - name: install the redis upstart
      template: src=ansible/redis.upstart.j2
        dest=/etc/init/redis.conf
        owner=root group=root mode=644
      tags:
        - upstart

    - name: install the jaci-web upstart
      template: src=ansible/jaci-web.upstart.j2
        dest=/etc/init/jaci-web.conf
        owner=root group=root mode=644
      tags:
        - upstart

    - name: install the jaci-workers upstart
      template: src=ansible/jaci-workers.upstart.j2
        dest=/etc/init/jaci-workers.conf
        owner=root group=root mode=644
      tags:
        - upstart

    - name: ensure we have the most updated version of the software from git
      git: repo=git://github.com/gabrielfalcao/jaci.git
        dest=/srv/jaci/src
        accept_hostkey=yes
      tags:
        - docker
        - upstart

    - name: pull dependency docker images
      shell: docker pull {{ item }}
      with_items:
        - cassandra
        - redis

    - name: build jaci-base docker image
      shell: docker build --force-rm -t gabrielfalcao/jaci-base /srv/jaci/src/docker/jaci-base
      tags:
        - docker

    - name: build jaci-web docker image
      shell: docker build --force-rm -t gabrielfalcao/jaci-web /srv/jaci/src/docker/jaci-web
      tags:
        - docker

    - name: start redis
      service: name=redis state=restarted
      tags:
        - upstart

    - name: copy assets from inside of the jaci-web docker image
      shell: docker run --rm --net=host -v /srv/jaci/static:/srv/jaci/static -e JACI_CASSANDRA_HOST=localhost -e JACI_REDIS_HOST=localhost gabrielfalcao/jaci-web jaci-web-boot.sh

    - name: restart jaci-web
      service: name=jaci-web state=restarted
      tags:
        - upstart

    - name: restart jaci-workers
      service: name=jaci-workers state=restarted
      tags:
        - upstart

    - name: ensuring that default nginx config is not present
      shell: rm -f /etc/nginx/sites-enabled/*
      tags:
        - upstart

    - name: place nginx configuration
      template: src=ansible/jaci-web.nginx.j2 dest=/etc/nginx/sites-enabled/jaci-web
      tags:
        - upstart

    - name: restart nginx
      service: name=nginx state=restarted
      tags:
        - upstart
