---
- hosts: all
  sudo: yes
  remote_user: root
  vars:
    full_server_url: http://localhost:9000
    jaci_http_hostname: 0.0.0.0
    jaci_http_port: 5000
    jaci_web_processes: 2
    jaci_github_cliend_id: 1c061315e9b34dc153aa
    jaci_github_cliend_secret: 5c9909556b60f3e6c618f278230620415cc15da8
    docker_version: 1.6.1
    docker_admin_users: []
    docker_opts:
      - "--iptables=false"


  tasks:
    - name: update apt cache
      shell: apt-get update

    - name: install docker dependencies
      apt: pkg={{ item }} state=present
      with_items:
        - linux-image-extra-virtual

    - name: install jaci dependencies
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - bash-completion
        - python-dev
        - libffi-dev
        - libssl-dev
        - libgnutls-dev
        - libsqlite3-dev
        - python-pip
        - python-virtualenv
        - git-core
        - nginx


    - name: add docker repository key
      apt_key: url=https://get.docker.io/gpg state=present

    - name: add docker repository
      apt_repository: >-
        repo="deb http://get.docker.io/ubuntu docker main" state=present

    - name: install docker
      apt: >-
        pkg=lxc-docker-{{ docker_version }}
        state=latest update_cache=yes cache_valid_time=3600

    - name: ensuring that the cassandra data dir is present
      file: path=/srv/jaci/data state=directory

    - name: ensuring that the assets dir exists
      file: path=/srv/jaci/assets state=directory

    - name: update docker defaults file
      template: src=ansible/docker.default.j2 dest=/etc/default/docker

    - name: add admin users to docker group
      user: name={{ item }} groups=docker append=yes
      with_items: docker_admin_users

    - name: start docker
      service: name=docker state=restarted

    - name: ensure docker is clean
      shell: docker rm -f $(docker ps -qa)
      ignore_errors: yes

    - name: install the cassandra upstart
      template: src=ansible/cassandra.upstart.j2
        dest=/etc/init/cassandra.conf
        owner=root group=root mode=644

    - name: install the redis upstart
      template: src=ansible/redis.upstart.j2
        dest=/etc/init/redis.conf
        owner=root group=root mode=644

    - name: install the jaci-web upstart
      template: src=ansible/jaci-web.upstart.j2
        dest=/etc/init/jaci-web.conf
        owner=root group=root mode=644

    - name: build jaci-base docker image
      shell: docker build -t gabrielfalcao/jaci-base /vagrant/docker/jaci-base

    - name: build jaci-web docker image
      shell: docker build -t gabrielfalcao/jaci-web /vagrant/docker/jaci-web

    - name: pull dependency docker images
      shell: docker pull {{ item }}
      with_items:
        - cassandra
        - redis

    - name: start redis
      service: name=redis state=restarted

    - name: copy assets from inside of the jaci-web docker image
      shell: docker run --rm --net=host -v /srv/jaci/static:/srv/jaci/static -e JACI_CASSANDRA_HOST=localhost -e JACI_REDIS_HOST=localhost gabrielfalcao/jaci-web jaci-web-boot.sh

    - name: restart jaci-web
      service: name=jaci-web state=restarted

    - name: ensuring that default nginx config is not present
      shell: rm -f /etc/nginx/sites-enabled/*

    - name: place nginx configuration
      template: src=ansible/jaci-web.nginx.j2 dest=/etc/nginx/sites-enabled/jaci-web

    - name: restart nginx
      service: name=nginx state=restarted

    # - name: pull jaci-workers docker image
    #   shell: docker pull gabrielfalcao/jaci-workers

    # - name: build docker image
    #   shell: docker build -t gabrielfalcao/jaci /vagrant
      #rm -rf /var/lib/docker if you want to cleanup docker