redis:
  image: redis

cassandra:
  image: cassandra

jaciweb:
  image: gabrielfalcao/jaci-web
  ports:
   - "5000:5000"

  links:
    - redis
    - cassandra

  volumes:
    - /srv/jaci:/srv/jaci

  environment:
    - JACI_HTTP_HOST=0.0.0.0
    - JACI_HTTP_PORT=5000
    - JACI_TOTAL_WORKERS=10
    - JACI_CASSANDRA_HOST=cassandra

    - JACI_SERVER_URL=http://0.0.0.0:5000
    - JACI_REDIS_HOST=redis
    - JACI_GITHUB_CLIEND_ID=d4d5fd91b48e183de039
    - JACI_GITHUB_CLIENT_SECRET=ec27a8f0e4a436c3cd6c846c377ef18e4bc4b0de

    - JACI_CONFIG_PATH=/etc/jaci.yml
    - JACI_WORKDIR=/srv/jaci/sandbox
    - JACI_LOG_PATH=/srv/jaci/jaci-web.log
