---
- hosts: carpentry.io
  sudo: yes
  remote_user: ubuntu

  vars:
    production: yes
    docker_based_deploy: yes
    carpentry_build_images: no
    carpentry_docker_deployment: yes
    carpentry_recreate_keyspace: no
    full_server_url: http://carpentry.io
    carpentry_http_hostname: carpentry.io
    carpentry_http_port: 5000
    carpentry_web_processes: 2
    carpentry_worker_processes: 10
    carpentry_secret_key: accd12a8dbfc6e5ece6db7ad4e5fb16631ba6b07a3a91d3b06a2887eb5d9c17d

  roles:
    - carpentry

  tasks:
    - name: install redis and nginx
      apt:
        pkg: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - nginx
        - redis-server


    - name: ensuring that default nginx config is not present
      shell: rm -f /etc/nginx/sites-enabled/*
      tags:
        - nginx

    - name: place nginx configuration
      template: src=templates/carpentry-web.nginx.j2 dest=/etc/nginx/sites-enabled/carpentry-web
      tags:
        - nginx

    - name: restart nginx
      service: name=nginx state=restarted
      tags:
        - nginx
