---
- hosts: carpentry.io
  sudo: yes
  remote_user: ubuntu

  vars:
    production: yes
    docker_based_deploy: yes
    carpentry_build_images: no
    carpentry_docker_deployment: no
    carpentry_recreate_keyspace: no
    carpentry_flush_all_data: yes
    full_server_url: http://carpentry.io
    carpentry_http_hostname: carpentry.io
    carpentry_http_port: 5000
    carpentry_web_processes: 2
    carpentry_worker_processes: 10
    cassandra:
      version: '2.0.1'
      version_branch: '2.0'

      repo_key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x4BD736A82B5C1B00'
      repo_key_file: '4BD736A82B5C1B00.gpg'
      dependencies:
        - 'openjdk-7-jre'
        - 'openjdk-7-jdk'

    cassandra_1_2:
      repo: 'deb http://www.apache.org/dist/cassandra/debian 12x main'

    cassandra_2_0:
      repo: 'deb http://www.apache.org/dist/cassandra/debian 20x main'

    config:
      cluster_name: 'MyCluster'
      data_file_directories:
        - '/var/lib/cassandra/data'
      commitlog_directory: '/var/lib/cassandra/commitlog'
      saved_caches_directory: '/var/lib/cassandra/saved_caches'
      log_level: 'info'
  roles:
    # # disabling cassandra after it was already instaled once
    # - cassandra
    - carpentry

  tasks:
    - name: install redis and nginx
      apt:
        pkg: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - nginx
        - redis-server


    - name: ensuring that default nginx config is not present
      shell: rm -f /etc/nginx/sites-enabled/*
      tags:
        - nginx

    - name: place nginx configuration
      template: src=templates/carpentry-web.nginx.j2 dest=/etc/nginx/sites-enabled/carpentry-web
      tags:
        - nginx

    - name: restart nginx
      service: name=nginx state=restarted
      tags:
        - nginx


    - name: restart web
      service: name=carpentry-web state=restarted
      tags:
        - restart

    - name: restart workers
      service: name="carpentry-workers-{{ item }}" state=restarted
      with_sequence: count="{{ carpentry_worker_processes }}"
      tags:
        - restart

    - name: cleanup and recreate full cassandra db and flush worker redis queues
      shell: /srv/carpentry/venv/bin/carpentry setup --drop --flush-redis
      when: carpentry_flush_all_data
      tags:
        - flush