---
- hosts: carpentry.io
  sudo: yes
  remote_user: ubuntu

  vars:
    production: yes
    docker_based_deploy: yes
    carpentry_build_images: no
    carpentry_docker_deployment: no
    carpentry_recreate_keyspace: no
    carpentry_flush_all_data: no
    full_server_url: http://carpentry.io
    carpentry_http_hostname: carpentry.io
    carpentry_http_port: 5000
    carpentry_web_processes: 4
    carpentry_worker_processes: 10

    config:
      log_level: 'info'

  roles:
    - carpentry

  tasks:
    - name: install redis and nginx
      apt:
        pkg: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - nginx
        - redis-server


    - name: ensuring that default nginx config is not present
      shell: rm -f /etc/nginx/sites-enabled/*
      tags:
        - nginx

    - name: place nginx configuration
      template: src=templates/carpentry-web.nginx.j2 dest=/etc/nginx/sites-enabled/carpentry-web
      tags:
        - nginx

    - name: restart nginx
      service: name=nginx state=restarted
      tags:
        - nginx


    - name: restart web
      service: name=carpentry-web state=restarted
      tags:
        - restart

    - name: restart workers
      service: name="carpentry-workers-{{ item }}" state=restarted
      with_sequence: count="{{ carpentry_worker_processes }}"
      tags:
        - restart

    - name: flush redis
      shell: /srv/carpentry/venv/bin/carpentry setup
      when: carpentry_flush_all_data
      tags:
        - flush