---
- hosts: jaci.io
  sudo: yes
  remote_user: ubuntu

  vars:
    production: yes
    jaci_build_images: no
    jaci_recreate_keyspace: no
    full_server_url: http://jaci.io
    jaci_http_hostname: jaci.io
    jaci_http_port: 5000
    jaci_web_processes: 2
    jaci_worker_processes: 10

  roles:
    - jaci

  tasks:
    - name: install redis and nginx
      apt:
        pkg: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - nginx
        - redis-server


    - name: ensuring that default nginx config is not present
      shell: rm -f /etc/nginx/sites-enabled/*
      tags:
        - nginx

    - name: place nginx configuration
      template: src=templates/jaci-web.nginx.j2 dest=/etc/nginx/sites-enabled/jaci-web
      tags:
        - nginx

    - name: restart nginx
      service: name=nginx state=restarted
      tags:
        - nginx
