---
- hosts: all
  sudo: yes
  remote_user: vagrant

  vars:
    production: no
    carpentry_build_images: yes
    carpentry_recreate_keyspace: yes
    full_server_url: http://localhost:9000
    carpentry_http_hostname: localhost
    carpentry_http_port: 5000
    carpentry_web_processes: 1
    carpentry_worker_processes: 1
    carpentry_github_client_id: 1c061315e9b34dc153aa
    carpentry_github_client_secret: 5c9909556b60f3e6c618f278230620415cc15da8
    carpentry_docker_deployment: false

  roles:
    - carpentry
