- name: ensure apt is ok
  shell: dpkg --configure -a
  ignore_errors: yes
  tags:
    - carpentry

- name: update cache
  shell: apt-get update
  tags:
    - carpentry

- name: add git core ppa
  apt_repository: repo='ppa:git-core'
  tags:
    - carpentry
    - update-code

- name: install carpentry dependencies
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - bash-completion
    - python-dev
    - libffi-dev
    - libssl-dev
    - libssh-dev
    - openssh-client
    - libgnutls-dev
    - libsqlite3-dev
    - python-pip
    - python-virtualenv
    - time
    - libxml2-dev
    - libxslt1-dev
    - git-core

  tags:
    - carpentry

- name: add docker repository key
  apt_key: url=https://get.docker.io/gpg state=present
  tags:
    - carpentry

- name: add docker repository
  apt_repository: >-
    repo="deb http://get.docker.io/ubuntu docker main" state=present
  tags:
    - carpentry

- name: install docker
  apt: >-
    pkg=lxc-docker-{{ docker_version }}
    state=latest update_cache=yes cache_valid_time=3600
  tags:
    - carpentry

- name: ensuring that the data and log dirs exist
  file: path={{ item }} state=directory
  with_items:
    - /srv/carpentry/builds
    - /srv/carpentry/ssh-keys
    - /srv/carpentry/data
    - /var/log/carpentry-web
    - /var/log/carpentry-workers
  tags:
    - carpentry


- name: ensure we have the most updated version of the software from git
  git: repo=git://github.com/gabrielfalcao/carpentry.git
    dest=/srv/carpentry/src
    accept_hostkey=yes
  tags:
    - carpentry
    - carpentry-web
    - carpentry-workers
    - docker
    - upstart

- name: update docker defaults file
  template: src=docker.default.j2 dest=/etc/default/docker
  tags:
    - carpentry

- name: add admin users to docker group
  user: name={{ item }} groups=docker append=yes
  with_items: docker_admin_users
  tags:
    - carpentry

- include: docker-based.yml
  when: carpentry_docker_deployment

- include: native-based.yml
  when: not carpentry_docker_deployment

- name: start docker
  service: name=docker state=restarted
  ignore_errors: yes
  tags:
    - carpentry

- name: stop carpentry-web
  service: name=carpentry-web state=stopped
  tags:
    - carpentry
    - carpentry-web
    - upstart
  ignore_errors: yes

- name: stop carpentry-workers
  service: name="carpentry-workers-{{ item }}" state=stopped
  with_sequence: count="{{ carpentry_worker_processes }}"
  tags:
    - carpentry
    - carpentry-workers
    - upstart
  ignore_errors: yes

- name: install the cassandra upstart
  template: src=cassandra.upstart.j2
    dest=/etc/init/cassandra.conf
    owner=root group=root mode=644
  tags:
    - carpentry
    - cassandra
    - upstart

- name: update docker defaults file
  template: src=docker.default.j2 dest=/etc/default/docker
  tags:
    - carpentry

- name: pull cassandra image
  shell: docker pull cassandra
  tags:
    - carpentry
    - cassandra
    - docker

- name: restart carpentry-web
  service: name=carpentry-web state=restarted
  tags:
    - carpentry
    - carpentry-web
    - upstart

- name: restart carpentry-workers
  service: name="carpentry-workers-{{ item }}" state=restarted
  with_sequence: count="{{ carpentry_worker_processes }}"

  tags:
    - carpentry
    - carpentry-workers
    - upstart
